### ISSUE TITLE
Could you help me with this?

### ISSUE THREAD

**Issue by Maki-01** [smiling-rahul/selenium_trovo#1]
Hey bro,
Found ur project and its really good, from what I can tell this automatically creates accounts on trovo?
Im getting errors when I try it myself though...

> ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -101

> Traceback (most recent call last):
>   File "C:\Users\h-mai\Desktop\selenium_trovo-main\trovo.py", line 103, in <module>
>     year = driver.find_element_by_xpath('/html/body/div[3]/div[2]/div[3]/div/div[4]/div[1]/div[3]/div[1]/input')
>   File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
>     return self.find_element(by=By.XPATH, value=xpath)
>   File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
>     return self.execute(Command.FIND_ELEMENT, {
>   File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
>     self.error_handler.check_response(response)
>   File "C:\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[3]/div[2]/div[3]/div/div[4]/div[1]/div[3]/div[1]/input"}
>   (Session info: headless chrome=90.0.4430.212)

**Comment by rahul-keshav** [comment]
Hey brother,
It's good to hear from you,

Why didn't you replied me on upwork.

Chatting on email is tough 😆😆

Rahul

**Comment by rahul-keshav** [comment]
We can chat over the phone or whatsapp or even facebook.

**Comment by Maki-01** [comment]
Its not trough email :D I replied to you on github :)
Also, could u test ur Trovo selenium project because for some reason its broken for me...

**Comment by rahul-keshav** [comment]
This was for a company and the thing is it is working perfectly for them and I know this is not the latest version, 

because I updated them recently. and then deployed. if I find some time then I will update this GitHub thing also.
but I request you don't use this, this was in the beta version. 
and I think there must be somewhere my 2captcha API.
